FROM jenkinsci/jenkins:2.46.2

USER root

RUN apt-get -qq update \
   && apt-get -qq -y install curl \
   && apt-get -qq -y install make

RUN curl -sSL https://get.docker.com/ | sh

RUN usermod -a -G staff jenkins

USER jenkins
