FROM jenkinsci/jenkins:2.46.2

RUN /usr/local/bin/install-plugins.sh performance:3.0 blueocean:1.0.1 blueocean-pipeline-editor:0.2.0

USER root

RUN apt-get -qq update \
   && apt-get -qq -y install curl \
   && apt-get -qq -y install make

RUN curl -sSL https://get.docker.com/ | sh

RUN usermod -a -G staff jenkins

USER jenkins
